alias tlogr='~/bin/tlog.sh'
alias add_keys='~/bin/add_keys.sh'
alias mci='mvn -f ~/grabyo/pom.xml clean install'
alias mcil='mvn clean tomcat:redeploy'
alias sync='~/bin/sync.sh'
alias tlog='tail -f /usr/share/tomcat7/logs/catalina.out'
alias tomst='/usr/share/tomcat7/bin/startup.sh'
alias tomsh='/usr/share/tomcat7/bin/shutdown.sh'
alias pstom='ps -aux | grep "tomcat"'
alias mcis='mci -DskipTests=true'
alias mcils='mvn clean tomcat:redeploy -DskipTests=true'
alias gr='cd ~/grabyo'
